<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $month
     * @param $year
     * @return array
     */
    public function countByMonths($month, $year){
        $em = $this->getEntityManager();
        $date = $year.'-'.$month.'-01';
        $count = $em->createQuery(
            'SELECT r FROM AppBundle:Task r 
                 WHERE MONTH(:dt) = :mon 
                 AND YEAR(:dt) = :yr')
            ->setParameter("dt",$date)
            ->setParameter("mon",$month)
            ->setParameter("yr",$year)
            ->getResult();
        return $count;
    }

}
